@startuml
skinparam defaultFontSize        18
skinparam roundcorner            20
skinparam Note {
BackgroundColor LightBlue
BorderColor Blue
}
skinparam Participant {
FontName Arial
Style awesome
BorderColor DeepSkyBlue
BackgroundColor LightBlue
}
participant "Guideline Publisher\nor Guideline Engine" as a
Participant "Guideline Repository" as b
a -> b: Search for Guidelines
b -> a: Search for Guidelines Response
@enduml