@startuml
skinparam defaultFontSize        18
skinparam roundcorner            20
skinparam Note {
BackgroundColor LightBlue
BorderColor Blue
}
skinparam Participant {
FontName Arial
Style awesome
BorderColor DeepSkyBlue
BackgroundColor LightBlue
}
participant "Care Plan Contributor" as cpc
participant "Guideline Performer" as gf
participant "Guideline Engine" as ge
participant "Care Plan Service" as cps
participant "Guideline Publisher" as gp
participant "Guideline Repository" as gr

==<size 28><color #155b2e>1. CCGs are published==

loop during CCG authoring
  note left of cps #EBF1DE
<size 24>•   A Guideline Publisher may support x1, x2
<size 24>•   A Guideline Publisher may support a digitally signed
   <size 24>   x3 payload (whole CCG, or reach CARD)
end note
 opt if updating an existing CCG
  gp -> gr: x1 Search for Guidelines
  gr -> gp: x1 response

  gp -> gr: x2 Retrieve Guideline
  gr -> gp: x2 response
 end opt
 gp -> gr: x3 Publish Guideline*
 gr -> gp: x3 response
end loop
note over gr #EBF1DE: <size 18>State-A: Well-formed CCGs exist in \n<size 18>Guideline Repository
==<size 28><color #e98023> 2. Guideline Engines regularly refresh their local cache of published CCGs. ==

loop for each CCG refresh cycle
 ge -> gr: x1 Search for Guideline
 gr -> ge: x1 response
 note left of ge #FFE7B7
 <size 24>A Guideline $apply Engine may support that only
 <size 24> “trusted” CCG artefacts are available for execution.
end note
 loop for every Guideline in need of refresh
  ge -> gr: x2 Retrieve Guideline
  gr -> ge: x2 response
 end loop for Guideline refresh 
end loop for refresh cycle
note over ge #FFE7B7: <size 18>State-B: updated CCGs exist on \n<size 18>Guideline $apply Engine
==<size 28><color #e94a23>3. Providers associate Patients with relevant CCGs ==
loop for every update of a person's care plan
 cpc -> cps: PCC-41 Search for Care Plan
 cps -> cpc: PCC-41 response
 cpc -> cps: PCC-38 Retrieve Care Plan
 cps -> cpc: PCC-38 response
 cpc -> cps: PCC-37 Update Care Plan
 cps -> cpc: PCC-37 response
end loop
note over cps #e94a23: <size 18>State-C: one or more CCGs are \n<size 18>associated with a care subject
@enduml