@startuml
skinparam defaultFontSize        14
skinparam roundcorner            20
skinparam Note {
BackgroundColor LightBlue
BorderColor Blue
}
skinparam Participant {
FontName Arial
Style awesome
BorderColor DeepSkyBlue
BackgroundColor LightBlue
}
participant "Care Plan\n Contributor" as cpc
participant "Guideline\n Performer" as gf
participant "Guideline\n Engine" as ge
participant "Care Plan\n Service" as cps
participant "Guideline\n Publisher" as gp
participant "Guideline\n Repository" as gr

==<size 18><color #155b2e>1. CCGs are published==

loop during CCG authoring
  note left of gp #EBF1DE
<size 16>•   A Guideline Publisher may support x1, x2
<size 16>•   A Guideline Publisher may support a digitally signed
   <size 16>   x3 payload (whole CCG, or reach CARD)
end note
 opt if updating an existing CCG
  gp -> gr: x1 Search for Guidelines
  gr -> gp: x1 response

  gp -> gr: x2 Retrieve Guideline
  gr -> gp: x2 response
 end opt
 gp -> gr: x3 Publish Guideline*
 gr -> gp: x3 response
end loop
note over gr #EBF1DE: <size 18>State-A: Well-formed CCGs exist in \n<size 18>Guideline Repository
==<size 18><color #e98023> 2. $apply Engines regularly refresh\n<size 18><color #e98023>their local cache of published CCGs. ==

loop for each CCG refresh cycle
 ge -> gr: x1 Search for Guideline
 gr -> ge: x1 response
 note left of cps #FFE7B7
 <size 16>A Guideline $apply Engine may support
 <size 16>  that only “trusted” CCG artefacts
 <size 16>  are available for execution.
end note
 loop for every Guideline in need of refresh
  ge -> gr: x2 Retrieve Guideline
  gr -> ge: x2 response
 end loop for Guideline refresh 
end loop for refresh cycle
note over ge #FFE7B7: <size 18>State-B: updated CCGs exist on \n<size 18>Guideline $apply Engine
==<size 18><color #e94a23>3. Providers associate Patients with relevant CCGs ==
loop for every update of a person's care plan
 cpc -> cps: PCC-41 Search for Care Plan
 cps -> cpc: PCC-41 response
 cpc -> cps: PCC-38 Retrieve Care Plan
 cps -> cpc: PCC-38 response
 cpc -> cps: PCC-37 Update Care Plan
 cps -> cpc: PCC-37 response
end loop
note over cps #e94a23: <size 14>State-C: one or more CCGs are \n<size 14>associated with a care subject
@enduml