# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.qrph.ccg
canonical: https://profiles.ihe.net/QRPH/CCG
version: 1.0.1-current
name: IHE_QRPH_CCG
title: "Computable Care Guidelines"
description: The IHE Computable Care Guidelines (CCG) Profile specifies a normative grammar and a normative transaction processing model that allows evidence-based care recommendations to be expressed in a way that a digital health solution can ingest and operationalize. This is an implementable and conformance-testable specification. It is targeted to regulated healthcare markets where the support for multiple conditions is an important requirement. The CCG Profile supports jurisdictions that want to leverage digital health to systemically improve the adoption of guideline-adherent best practices across an entire care delivery network.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: Trial-Implementation
#releaseLabel: release
#date: 2025-10-03
status: active
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE QRPH Technical Committee
  - url: https://www.ihe.net/ihe_domains/quality_research_and_public_health/
  - email: qrph@ihe.net
contact:
  - name: IHE QRPH Technical Committee
    telecom:
      - system: email
        value: qrph@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2025+
dependencies: 
  hl7.fhir.uv.cpg: 2.0.0
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.cql: 1.0.0

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true

pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Computable Care Guidelines (CCG) Home
    generation: markdown
  CCG_v1_over.md:
    title: "Business Description"
    generation: markdown
  CCG_v1_actor.md:
    title: "Actors"
    generation: markdown
  CCG_v2_x1.md:
    title: 2:3.61 Search for Guidelines [QRPH-61]
    generation: markdown
  CCG_v2_x2.md:
    title: 2:3.62 Retrieve Guideline [QRPH-62]
    generation: markdown
  CCG_v2_x3.md:
    title: 2:3.63 Publish Guideline [QRPH-63]
    generation: markdown
  CCG_v2_x4.md:
    title: 2:3.64 Apply Guideline [QRPH-64]
    generation: markdown
  CCG_v3_launch.md:
    title: Content Specifications
    generation: markdown
  CCG_v4.md:
    title: Jurisdictional Contextualizations
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  CCG Home: index.html
  Volume 1:
    Business Description: CCG_v1_over.html
    Actors: CCG_v1_actor.html
  Volume 2:
    "Search for Guidelines [QRPH-61]": CCG_v2_x1.html
    "Retrieve Guideline [QRPH-62]": CCG_v2_x2.html
    "Publish Guideline [QRPH-63]": CCG_v2_x3.html
    "Apply Guideline [QRPH-64]": CCG_v2_x4.html
  Volume 3:
    Content Specifications: CCG_v3_launch.html
  Volume 4:
    Jurisdictional Contextualizations: CCG_v4.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
